CentOS code/up/urls.py
import os.path
from django.conf import settings
from django.conf.urls import *

from marking.views import *
from django.views.generic.simple import direct_to_template
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
  

## Page ## 
	(r'^$', main_page),
	(r'^user/(\w+)/$', user_page),
	(r'^bookmark_of/(\w+)/$', bookmark_of),
	(r'tag/([^\s]+)/$', tag_page),
	(r'tag/$', tag_cloud_page),
	(r'^search/$', search_page),
	(r'^search_index/$',search_indexpage),
  	(r'^hot/$', popular_page),
 	(r'^profile/(\w+)/$', userprofile),
 	(r'^edit/(\w+)/$', edit_userprofile),
  	(r'^bookmark/(\d+)/$', bookmark_page),
  	(r'^following_list/(\w+)/$', following),
	(r'^follower_list/(\w+)/$', follower),
	(r'^mycomment/(\d+)/$', mycomment),
	(r'^rank/$', rank),
	(r'^rank/add/$', friend_add_rank),
	(r'^test/$', test),
	#(r'^accounts/profile/$', re_aflogin),
	(r'^comments/posted/$', redirect_comment),
	
## Friend ##	
  	(r'^friends/(\w+)/$', friends_page),
  	(r'^friend/add/$', friend_add),
  	(r'^friend/delete/$', friend_delete),
## Session ##
  	(r'^login/$', 'django.contrib.auth.views.login'), #'django.contrib.auth.views.login'
  	(r'^logout/$', logout_page),
  	
  	(r'^register/$', register_page),
  	(r'^register/success/$',register_success),
## Content ##
  	(r'^save/$', bookmark_save_page),
	(r'^delete/$', bookmark_delete),
  	(r'^vote/$', bookmark_vote_page),
  	(r'^comments/', include('django.contrib.comments.urls')),
## Ajax ##
	(r'^ajax/tag/autocomplete/$', ajax_tag_autocomplete),
  
## Friends ##  
	(r'^friends/(\w+)/$', friends_page),
  	(r'^friend/add/$', friend_add),
## Admin ##
  	(r'^admin/', include(admin.site.urls)),

## ForTesting ##
	(r'^test_clearbookmark/(\w+)/$', test_clearbookmark),
	(r'^test_checkregister/(\w+)/$', test_checkregister),
	(r'^test_searching/$', test_searching),
	(r'^test_nosearching/$', test_nosearching),
	(r'^test_adding/$', test_adding),
	(r'^test_edit/$', test_edit),
	(r'^test_delete/$', test_delete),
	(r'^test_vote/$', test_vote),
	(r'^test_isfriend/(\w+)/$', test_isfriend),
	(r'^test_comment/(\w+)/$', test_comment),
	(r'^test_isvoted/(\w+)/$', test_isvoted),
	(r'^test_privacy/$', test_privacy),
)

#urlpatterns += patterns('django.views.generic.sample',
#&nbsp (r'^/login/$' , 'direct_to_template',{'template':'base_login.html'}),)


###  MEDIA ###
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_DOC_ROOT}),    
)

CentOS code/marking/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template import Context
from django.db.models.signals import post_save
from django.conf import settings
from django.template.loader import get_template
from django.core.mail import send_mail

#from mptt.models import MPTTModel, TreeForeignKey

from django.contrib import admin
##
class Link(models.Model):
	url = models.URLField(unique=True)

	def __str__(self):
		return self.url
	class Admin:
		pass
##
class Bookmark(models.Model):
	
	title = models.CharField(max_length=200)
	user = models.ForeignKey(User)
	link = models.ForeignKey(Link)
	date_add = models.DateTimeField(auto_now_add=True)
	status = models.BooleanField()
	shared_state = models.BooleanField()
	def __str__(self):
		return '%s, %s' % (self.user.username, self.link.url)
		
	def get_absolute_url(self):
		return self.link.url 
		
	class Admin:
		list_display = ('title', 'link','user')
		list_filter = ('user', )
		ordering = ('title', )
		search_fields = ('title', )

###
#class UserProfile(models.Model):
#	user = models.OneToOneField(User)	
#	display = models.ImageField(upload_to='profile_picture',blank=True, null=True)


	
    	
##
class Tag(models.Model):
	name = models.CharField(max_length=64, unique=True)
	bookmarks = models.ManyToManyField(Bookmark)

	def __str__(self):
		return self.name
	class Admin:
		pass
##
class SharedBookmark(models.Model):
	bookmark = models.ForeignKey(Bookmark, unique=True)
	date = models.DateTimeField(auto_now_add=True)
	votes = models.IntegerField(default=1)
	users_voted = models.ManyToManyField(User)
	status = models.BooleanField()
	#owner_id = models.IntegerField()
	

	def __str__(self):
		return '%s, %s' % self.bookmark, self.votes
    
	class Admin:
		pass
		
#############################

class Friendship(models.Model):
	from_friend = models.ForeignKey(User, related_name='friend_set')
	to_friend = models.ForeignKey(User, related_name='to_friend_set')
  
	def __str__(self):
		return '%s, %s' % (self.from_friend.username, self.to_friend.username)

	class Admin:
		pass

	class Meta:
		unique_together = (('to_friend', 'from_friend'), )

#############################

class Invitation(models.Model):
	name = models.CharField(max_length=50)
	email = models.EmailField()
	code = models.CharField(max_length=20)
	sender = models.ForeignKey(User)

	def __str__(self):
		return '%s, %s' % (self.sender.username, self.email)

	class Admin:
		pass

	def send(self):
		subject = 'Invitation to join Django Bookmarks'
		link = 'http://%s/friend/accept/%s/' % (
			settings.SITE_HOST,
			self.code
		)
		template = get_template('invitation_email.txt')
		context = Context({
			'name': self.name,
			'link': link,
			'sender': self.sender.username,
		})
		message = template.render(context)
		send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [self.email])


class Post(models.Model):
	
	text = models.TextField()
	added  = models.DateTimeField(auto_now_add=True)

#class Comment(MPTTModel):
	
#	post = models.ForeignKey(Post)
#	author = models.ForeignKey(User)
#	comment = models.TextField()
#	added  = models.DateTimeField(auto_now_add=True)
    # a link to comment that is being replied, if one exists
#	parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

#	class MPTTMeta:
        # comments on one level will be ordered by date of creation
#		order_insertion_by=['added']

CentOS code/templates/bookmark_of.html
{% extends "base_login.html" %}                                      
{% block content %} 
{% load comments %}
{% load mylimite %}
                    
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                              <tr>
                                <td width="7%" align="right" valign="middle" bgcolor="#F3F3F3">&nbsp;</td>
                                <td width="83%" align="left" valign="middle" bgcolor="#F3F3F3">
                                <p id="upname2"><img src="{{ MEDIA_URL }}images/homeicon.gif" width="15" height="15" alt="Home" />&nbsp;/&nbsp;My Library&nbsp;<img src="{{ MEDIA_URL }}images/this.png" width="8" height="9" alt="Here" /></p>
                                </td>
                                <td width="6%" align="right" valign="middle" bgcolor="#F3F3F3"><a href="/save/"><img src="{{ MEDIA_URL }}images/addbk.png" width="100" height="21" alt="Add "></a></td>
                       
                                <td width="4%" bgcolor="#F3F3F3">&nbsp;</td>
                              </tr>
                            </table>     

             
			    {% if bookmarks %}
                            {% for bookmark in bookmarks %}
<br />
                        	
                        
                        
<table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td width="3%" rowspan="5">&nbsp;</td>
                  <td width="12%" rowspan="5" align="left" valign="top" >
                  
				{% if bookmark.status %}
					<a class="datebox" style="background-image:url({{ MEDIA_URL }}/images/boxcount3.png)">
				{% else %}
					<a class="datebox" style="background-image:url({{ MEDIA_URL }}/images/boxcount2.png)">
				{% endif %}

			<br>{{ bookmark.date_add|date:"D d M Y" }}
      					</a>
                    
                </td>
                                      <td width="85%"><br />
                                      <span id="titleurl" ><u>{{ bookmark.title }}</u></span></td>
                                    <tr>
                                      <td>
                                      <a id = "upname2" style="color:#06F">URL&nbsp;&nbsp;&nbsp;&nbsp;</a><a href="{{ bookmark.link.url }}" target="_blank">{{ bookmark.link.url }}</a>

                                      </td>
                                    </tr>
                                    <tr>
                                      <td>
							{% if show_tags %}
							{% if bookmark.tag_set.all %}
                                                                            <p class="tagspan">                                
										{% for tag in bookmark.tag_set.all %}
										<a href="/tag/{{ tag.name|urlencode }} "><span id="upname2">{{ tag.name|escape }}</span></a> 
										{% endfor %} 
										
                                      						</p>
								{% else %}	
								{% endif %}
							{% endif %}
                                      
                                      </td>
                                    </tr>
                                    <tr>
                                      <td>

                                      {% if show_edit %}
                                      <img src="{{ MEDIA_URL }}images/editbutt.png" width="16" height="16" alt="Edit URL" />                                      
                                      <a id = "upname3" href="/save/?url={{ bookmark.link.url|urlencode }}">&nbsp;Edit&nbsp;&nbsp;&nbsp;</a>
                                      
 													{% endif %}
                                      {% if show_delete %}
                                      <img src="{{ MEDIA_URL }}images/trashbutt.gif" width="16" height="17" alt="Delete URL" />                                      
                                      <a id = "upname3" href="/delete/?url={{ bookmark.link.url|urlencode }}">&nbsp;Delete&nbsp;&nbsp;&nbsp;</a>
                                      {% endif %}
					<img src="{{ MEDIA_URL }}/images/commentballoon.gif" width="18" height="18" alt="Up" />&nbsp;<a href="/mycomment/{{ bookmark.id }}/">View&nbsp;Comments</a> 



                                      </td>
                                      
                                    </tr>
                                    <tr>
                                      <td height="10" valign="baseline"><hr color="#D7D7D7" size="1"></td>
                            </tr>
</table>
						<tr>
        
                          {% endfor %}
                          <br>
                          <br>
                          <br>
                        
          <center>              
                          
                         {% if bookmarks.has_previous %}
                         <a href="./?page={{ bookmarks.previous_page_number }}">previous</a> 
                         {% endif %} 
                         
                          Page {{ bookmarks.number }} of {{ bookmarks.paginator.num_pages }}.  
                               
                         {% if bookmarks.has_next %}
                          <a href="./?page={{ bookmarks.next_page_number }}">next</a> 
                          {% endif %}
             </center>            
                          <br>                         
                          <br>
                          {% else %}
                          <center>No bookmarks found.</center>
                          {% endif %}
{% endblock %}
{% block pic1 %}myurl.png{% endblock %}
{% block pic2 %}mynw.png{% endblock %}
{% block pic3 %}hoturl.png{% endblock %}
{% block pic4 %}groupac.png{% endblock %}
{% block popula %}
{% if people %}
	{% for to_friend in people %}
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{{ MEDIA_URL }}images/starlogo.png" width="15" height="15" border="0">&nbsp;<a href="/profile/{{ to_friend.username|mylimite:15 }}" target="_blank"><font color="#39b54a">&nbsp;<b>{{ to_friend }}</b></font></a><br><br>
	{% endfor %}
{% endif %}
{% endblock %}

CentOS code/templates/bookmark_page.html
{% extends "base_login.html" %}
{% load comments %}
{% load mylimite %}
{% block title %}Bookmark:
{{ shared_bookmark.bookmark.title|escape }}{% endblock %}
{% block head %}
	<a href="/vote/?id={{ shared_bookmark.id }}"
	class="vote">[+]</a>
	<a href="{{ shared_bookmark.bookmark.link.url }}" class="title">
	{{ shared_bookmark.bookmark.title|escape }}</a>
{% endblock %}
{% block content %}

{% if bookmark.status or bookmark.user_id == user.id %}
<table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="6%" rowspan="2" align="right" valign="top">
              
              </td>
              <td width="12%" rowspan="2" align="left" valign="top">
              
					<a class="savePeopleCount" style="background-image:url({{ MEDIA_URL }}/images/boxcount.png)">
        			<strong>{{ shared_bookmark.votes }}</strong>People
      			</a>
              </td>
              <td width="50%" align="left" valign="bottom"><a href="{{ shared_bookmark.bookmark.link.url }}" class="title">
          {{ shared_bookmark.bookmark.title|escape }}</a></td>
              <td width="32%">&nbsp;</td>
        </tr>
            <tr>
              <td align="left" valign="bottom"><a href="/vote/?id={{ shared_bookmark.id }}" class="vote"><img src="{{ MEDIA_URL }}/images/uping.png" width="18" height="18" alt="Up" /></a>&nbsp;Post by : <a href="/profile/{{ shared_bookmark.bookmark.user.username }}/" class="username">
                  {{ shared_bookmark.bookmark.user.username }}</a>
		<br />
		&nbsp;&nbsp;{{ shared_bookmark.bookmark.date_add|timesince }}&nbsp;&nbsp;ago
		<br />
                                      </p>
                
                </td>
              <td>&nbsp;</td>
        </tr>
            <tr>
              <td width="6%">&nbsp;</td>
              <td>&nbsp;</td>
              <td colspan="2" align="left" valign="bottom"><hr color="#D7D7D7" size="1">

		
		{% get_comment_count for marking.sharedbookmark shared_bookmark.id as comment_count %}
		{% get_comment_list for marking.sharedbookmark shared_bookmark.id as comment_list %}
		
		<h2>{{ comment_count }} Comments</h2>
<div style="background-color:#ffffff" width="150">
{% for comment in comment_list %}
<table widht="600px" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff">
<tr valign="top">	
	<td width="10px">&nbsp;</td>
	<td>
		
		<img src="{{ MEDIA_URL }}images/userdisplay.jpg" border="1" width="30px" height="30px">
	</td>
	<td width="15px">&nbsp;</td>
		<td>
		<a href="/profile/{{ comment.user.username }}/"><b>{{ comment.user.username }}</b></a>
		<font color="#2c2c2c">{{ comment.comment|escape|urlizetrunc:40 }}</font><br>
		{{ comment.submit_date|timesince }} ago.
		</td>
</tr>
</table>
<hr color="#D7D7D7" size="1">
{% empty %}

{% endfor %}
</div>

		{% render_comment_form for marking.sharedbookmark shared_bookmark.id %}		

		</td>
        </tr>
        <br />
      </table>
    </td>
  </tr>
</table>
{% else %}
	<center><br><br><br><br><br><br>
	<img src="{{ MEDIA_URL }}/images/notfound.jpg" alt="Not Found" />
	<br><br><br><img src="{{ MEDIA_URL }}/images/errorlogo.png" alt="Not Found" />&nbsp;We can't find the page you looking for.<br>Or Maybe You don't have permission to see it.<br><br><br><br><br><br>
	<center>
{% endif %}
{% endblock %}
{% block popula %}
{% if people %}
	{% for to_friend in people %}
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{{ MEDIA_URL }}images/starlogo.png" width="15" height="15" border="0">&nbsp;<a href="/profile/{{ to_friend }}" target="_blank"><font color="#39b54a">&nbsp;<b>{{ to_friend.username|mylimite:15 }}</b></font></a><br>
	{% endfor %}
{% endif %}
{% endblock %}
{% block pic1 %}myurl.png{% endblock %}
{% block pic2 %}mynw.png{% endblock %}
{% block pic3 %}hoturl.png{% endblock %}
{% block pic4 %}groupac.png{% endblock %}

{% block yourtag %}
{% if allbookmark %}
	{% for bookmark in allbookmark %}
		{% if bookmark.tag_set.all %}  
               
			{% for tag in bookmark.tag_set.all %}
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{{ MEDIA_URL }}images/starlogo.png" width="15" height="15" border="0">&nbsp;<a href="/tag/{{ tag.name|urlencode }}" id="upname2"><font color="#39b54a">&nbsp;<b>{{ tag.name|escape }}</b></font></b></font></a><br>			
			{% endfor %}

		{% endif %}
	{% endfor %}
{% else %}
    		<br /><center>No Tag.</center><br />
{% endif %}
{% endblock %}

CentOS code/templates/datalist.html
{% extends "base_login.html" %}

{% block title %}Django Bookmarks List{% endblock %}
{% block head %}Django Bookmarks List{% endblock %}

{% block content %}
  {% if user.username %}
    <p>Show List bookmarks By:: {{ user.username }}! </p>
  {% else %}
    <p>Plese<a href="/login">Login</a> 
      before you can store and share bookmarks.</p>
  {% endif %}
{% endblock %}

CentOS code/templates/friends_page.html
{% extends "base_login.html" %}                                      
{% block content %} 
{% load mylimite %}
                    
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                              <tr>
                                <td width="7%" align="right" valign="middle" bgcolor="#F3F3F3">&nbsp;</td>
                                <td width="83%" align="left" valign="middle" bgcolor="#F3F3F3">
                                <p id="upname2"><img src="{{ MEDIA_URL }}images/homeicon.gif" width="15" height="15" alt="Home" />&nbsp;/&nbsp;My Network&nbsp;<img src="{{ MEDIA_URL }}images/this.png" width="8" height="9" alt="Here" /></p>
                                </td>
                                <td width="6%" align="right" valign="middle" bgcolor="#F3F3F3"></td>
                       
                                <td width="4%" bgcolor="#F3F3F3">&nbsp;</td>
                              </tr>
                            </table>
                            
			    {% if bookmarks %}
                            {% for bookmark in bookmarks %}
<br />
                        
                        
                        
<table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td width="3%" rowspan="5">&nbsp;</td>
                  <td width="12%" rowspan="5" align="left" valign="top" >
                  
<img src="{{ MEDIA_URL }}images/userdisplay.jpg" border="1">

                    
                </td>
                                      <td width="85%"><br />
                                      <span id="titleurl" ><u>{{ bookmark.title }}</u></span>
</td>
                                    <tr>
                                      <td>
                                      <a id = "upname2" style="color:#06F">URL&nbsp;&nbsp;&nbsp;&nbsp;</a><a href="{{ bookmark.link.url }}" target="_blank">{{ bookmark.link.url }}<br></a>
Post by : <a href="/profile/{{ bookmark.user.username }}/" class="username">
                  {{ bookmark.user.username }}</a>&nbsp;&nbsp;{{ bookmark.date_add|timesince }}&nbsp;&nbsp;ago&nbsp;|&nbsp;<img src="{{ MEDIA_URL }}/images/commentballoon.gif" width="18" height="18" alt="Up" />&nbsp;<a href="/mycomment/{{ bookmark.id}}/">Add&nbsp;Comments</a>&nbsp;|

                                      </td>
                                    </tr>
                                    <tr>
                                      <td>
							{% if show_tags %}
							{% if bookmark.tag_set.all %}
                                                                            <p class="tagspan">                                
										{% for tag in bookmark.tag_set.all %}
										<a href="/tag/{{ tag.name|urlencode }} "><span id="upname2">{{ tag.name|escape }}</span></a> 
										{% endfor %} 
                                      </p>
								{% else %}	
								{% endif %}
							{% endif %}
                                      
                                      </td>
                                    </tr>
                                    <tr>
                                      <td>
                                      {% if show_edit %}
                                      <img src="{{ MEDIA_URL }}images/editbutt.png" width="16" height="16" alt="Edit URL" />                                      
                                      <a id = "upname3" href="/save/?url={{ bookmark.link.url|urlencode }}">&nbsp;Edit&nbsp;&nbsp;&nbsp;</a>
                                      
 													{% endif %}
                                      {% if show_delete %}
                                      <img src="{{ MEDIA_URL }}images/trashbutt.gif" width="16" height="17" alt="Delete URL" />                                      
                                      <a id = "upname3" href="/delete/?url={{ bookmark.link.url|urlencode }}">&nbsp;Delete&nbsp;&nbsp;&nbsp;</a>
                                      {% endif %}
                                      </td>
                                      
                                    </tr>
                                    <tr>
                                      <td height="10" valign="baseline"><hr color="#D7D7D7" size="1"></td>
                            </tr>
</table>
						<tr>
        
                          {% endfor %}
                          <br>
                          <br>
                          <br>
                        
          <center>              
                          
                         {% if bookmarks.has_previous %}
                         <a href="./?page={{ bookmarks.previous_page_number }}">previous</a> 
                         {% endif %} 
                         
                          Page {{ bookmarks.number }} of {{ bookmarks.paginator.num_pages }}.  
                               
                         {% if bookmarks.has_next %}
                          <a href="./?page={{ bookmarks.next_page_number }}">next</a> 
                          {% endif %}
             </center>            
                          <br>                         
                          <br>
                          {% else %}
                          <center>No bookmarks found.</center>
                          {% endif %}
{% endblock %}

{% block popula %}
{% if people %}
	{% for to_friend in people %}
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{{ MEDIA_URL }}images/starlogo.png" width="15" height="15" border="0">&nbsp;<a href="/profile/{{ to_friend }}" target="_blank"><font color="#39b54a">&nbsp;<b>{{ to_friend.username|mylimite:15 }}</b></font></a><br>
	{% endfor %}
{% endif %}
{% endblock %}



{% block pic1 %}myurl.png{% endblock %}
{% block pic2 %}mynw_be.png{% endblock %}
{% block pic3 %}hoturl.png{% endblock %}
{% block pic4 %}groupac.png{% endblock %}

{% block yourtag %}
{% if allbookmark %}
	{% for bookmark in allbookmark %}
		{% if bookmark.tag_set.all %}  
               
			{% for tag in bookmark.tag_set.all %}
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{{ MEDIA_URL }}images/starlogo.png" width="15" height="15" border="0">&nbsp;<a href="/tag/{{ tag.name|urlencode }}" id="upname2"><font color="#39b54a">&nbsp;<b>{{ tag.name|escape }}</b></font></b></font></a><br>			
			{% endfor %}
		{% endif %}
	{% endfor %}
{% else %}
    		<br /><center>No Tag.</center><br />
{% endif %}
{% endblock %}

CentOS code/templates/rank.html
{% extends "base_login.html" %} 
{% block content %}
{% load mylimite %}
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
  
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="6%" bgcolor="#F3F3F3">&nbsp;</td>
          <td width="60%" align="left" valign="top" bgcolor="#F3F3F3"><p id="upname2"><img src="{{ MEDIA_URL }}images/trophy.png" width="15" height="15" alt="Home" />&nbsp;&nbsp;Popular People </font>&nbsp;<img src="{{ MEDIA_URL }}images/this.png" width="8" height="9" alt="Here" /></p></td>
          <td width="33%" bgcolor="#F3F3F3">&nbsp;</td>
        </tr>
    </table>
      
      
    <td align="center" valign="top">
	
	{% if people2 %}
	<table width="100%" border="0" cellspacing="0" cellpadding="0">

		{% for to_friend in people2 %}
			<tr>
				<td width="12%" align="right" valign="top"><hr color="#D7D7D7" size="1"> </td>
				<td width="3%" align="right" valign="top"><hr color="#D7D7D7" size="1"> </td>
				<td width="35%" align="right" valign="top"><hr color="#D7D7D7" size="1"> </td>
			</tr>
			<tr>
				<td width="15%" align="right" valign="top">
				<br><img src="{{ MEDIA_URL }}images/userdisplay.jpg" border="1">
				<br><a href="/profile/{{ to_friend }}/">{{ to_friend.username|mylimite:15 }}</a> <br> 
				</td>
				<td width="4%">&nbsp;</td>
				<td width="81%" valign="middle">
					<font color='#09F'><b>{{ to_friend.first_name }}&nbsp;{{ to_friend.last_name }}</b></font><br>
					&nbsp;&nbsp;Date Register : {{ to_friend.date_joined}}<br>
					&nbsp;&nbsp;Last Login : {{ to_friend.last_login}}<br>

				{#{% if myid == to_friend.id %}#}
				{#{% else %}#}
				{#	{% if to_friend in myfriend_list %}#}
				{#		<div class="editprofile5"><p>followed</p></div>#}
				{#	{% else %}#}
				{#		<a href="/rank/add/?username={{ to_friend }}"><div class="editprofile6"><p>follow</p></div></a>#}
				{#	{% endif %}#}
				{#{% endif %}#}
				</td>   
			</tr>
		{% endfor %}

	  {% else %}
	    <p>No friends found.</p>		
	{% endif %}
	  
			<tr>
				
			</tr>
	</table>
    </td>
  </tr>
</table>
{% endblock %}
{% block pic1 %}myurl.png{% endblock %}
{% block pic2 %}mynw.png{% endblock %}
{% block pic3 %}hoturl.png{% endblock %}
{% block pic4 %}groupac.png{% endblock %}
{% block popula %}
{% if people %}
	{% for to_friend in people %}
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{{ MEDIA_URL }}images/starlogo.png" width="15" height="15" border="0">&nbsp;<a href="/profile/{{ to_friend }}" target="_blank"><font color="#39b54a">&nbsp;<b>{{ to_friend.username|mylimite:15 }}</b></font></a><br>
	{% endfor %}
{% endif %}
{% endblock %}


{% block yourtag %}
{% if allbookmark %}
	{% for bookmark in allbookmark %}
		{% if bookmark.tag_set.all %}  
               
			{% for tag in bookmark.tag_set.all %}
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{{ MEDIA_URL }}images/starlogo.png" width="15" height="15" border="0">&nbsp;<a href="/tag/{{ tag.name|urlencode }}" id="upname2"><font color="#39b54a">&nbsp;<b>{{ tag.name|escape }}</b></font></b></font></a><br>			
			{% endfor %}

		{% endif %}
	{% endfor %}
{% else %}
    		<br /><center>No Tag.</center><br />
{% endif %}
{% endblock %}